[catalouge] Fix DIC1.MP.RF+dmb.st+addr-cachesyncisb.litmus
Commit ab0ebef282c26a12cb041315211e612b3f78d6f2 ("[herd] Adapt tests")
has broke litmus7 CI
```
DIC1.MP.RF+dmb.st+addr-cachesyncisb.c:737:48: error: unknown type name ‘inst_t’; did you mean ‘ins_t’?
  737 | typedef void (*code0_t)(ins_t *P1_m0,ins_t nop,inst_t* *z);
      |                                                ^~~~~~
      |                                                ins_t
DIC1.MP.RF+dmb.st+addr-cachesyncisb.c:739:51: error: unknown type name ‘inst_t’; did you mean ‘ins_t’?
```
due to typo in limtus test. Let's fix that.

Signed-off-by: Vladimir Murzin <vladimir.murzin@arm.com>