[gen]: Rework LDN
Unfortunately, there are several issues with litmus test generation
when it comes to broad use Neon annotations.

For example, litmus test for data dependency between Neon load and a
store comes with several issues

$ diyone7  -arch AArch64 -variant neon "Rfe PodRW Rfe DpDatadWN2N2"​

---cut---

P0          | P1                      ;​
LDR W1,[X0] | LD2 {V0.4S, V1.4S},[X0] ; (* A *)​
MOV W2,#1   | EOR V2.4S,V0.4S,V0.4S   ;​ (* B *)
STR W2,[X3] | ...                     ;​

---cut---

First, result of load into V1 at A is not consumed. Second,
instruction at B is not valid:

 Assembler messages:​
  Error: operand mismatch -- `eor V2.4S,V0.4S,V0.4S'​
  Info:    did you mean this?​
  Info:    eor v1.8b, v0.8b, v0.8b​
  Info:    other valid variant(s):​
  Info:    eor v1.16b, v0.16b, v0.16b​

Another issue can be seen in litmus test for address dependency
between a load and Neon load

$ diyone7  -arch AArch64 -variant neon "PodWW Rfe DpAddrdRPN2 Fre"​

---cut---

P0          | P1                         ;​
MOV W0,#1   | ...                        ;​
STR W0,[X1] | ...                        ;​
MOV W2,#1   | ...                        ;​
STR W2,[X3] | LD2 {V0.4S, V1.4S},[X4],X3 ; (* A *)​

---cut--

Neon load at A​ uses post-index form where X3 would be consumed after
access is made to update X4, in other words, X3 doesn't contribute to
the address generation for LD2 access at A.

Also, there are numerous cases where litmus test generation would fail
with

 Fatal error: exception File "lib/AArch64Base.ml", line 317, characters 48-54: Assertion failed​

To make things work we need to rework LDN. For things like address
dependency and control dependency we need to reduce vector registers
horizontally (in case more than one vector register is used) follow up
with reduce horizontally single vector register into scalar, so it can
be transferred to general purpose register and become available either
for address generation logic or control flow logic.

In term of instruction that reduction looks like

 LD2 {V0.4S, V1.4S},[X0] ;​
 ADD V0.4S,V0.4S,V1.4S   ;​ (* reduce (and consume) V0 and V1 into V0 *)
 ADDV S2,V0.4S           ;​ (* reduce V0 inot S2 *)
 FMOV W1,S2              ; (* transfer S2 into W1 *)

The only downside is that for data dependency between, say, Neon load
and Neon store data have to trip via general purpose register which is
sub-optimal

 LD2 {V0.4S, V1.4S},[X0] ;​
 ADD V0.4S,V0.4S,V1.4S   ;​
 ADDV S2,V0.4S           ;​
 FMOV W1,S2              ;​
 EOR W2,W1,W1            ;​
 DUP V3.4S,W2            ;​
 MOVI V4.4S,#1           ;​
 MOVI V5.4S,#2           ;​
 ADD V4.4S,V4.4S,V3.4S   ;​
 ADD V5.4S,V5.4S,V3.4S   ;​
 ST2 {V4.4S, V5.4S},[X3] ;​

However, when it comes to data dependency, say, between Neon load and
non-Neon store things look more natural

 LD2 {V0.4S, V1.4S},[X0] ;​
 ADD V0.4S,V0.4S,V1.4S   ;​
 ADDV S2,V0.4S           ;​
 FMOV W1,S2              ;​
 EOR W2,W1,W1            ;​
 ADD W2,W2,#1            ;​
 STR W2,[X3]             ;​

Signed-off-by: Vladimir Murzin <vladimir.murzin@arm.com>