[asl][compliance] Test name-clashing avoidance
Previously: these tests failed with the following error due to clashing names:
```
Error: Multiple rules generated for
_build/default/asllib/compliance/run/foo.1.yaml.actual:
- _build/default/asllib/compliance/generate/dune.inc:54
- _build/default/asllib/compliance/generate/dune.inc:2
```

Now: they succeed, with the following actual names:
- `first-dir/foo.1.yaml` --> `foo.1.yaml.actual`
- `first-dir/foo.yaml` --> `foo.yaml.actual`
- `second-dir/foo.yaml` --> `foo.yaml.actual.1`
- `third-dir/foo.yaml` --> `foo.yaml.actual.2`