[gen]: Rework STN
Unfortunately, there are several issues with litmus test generation
when it comes to broad use Neon annotations.

For example, litmus test for data dependency between a load and Neon
store comes with use of invalid instruction

$ diyone7  -arch AArch64 -variant neon "Rfe PodRW Rfe DpDatadWN2N2"​

---cut---

P0          | P1                      ;​
LDR W1,[X0] | ...                     ;​
MOV W2,#1   | ...                     ;​
STR W2,[X3] | MOVI V3.4S,#1           ;​
            | ADD V2.4S,V2.4S,V3.4S   ;​
            | ST2 {V2.4S},[X2]        ;​ (* A *)
---cut---

Neon's ST2 at A is invalid:

Error: invalid number of registers in the list; 2 registers are
expected at operand 1 -- `st2 {V2.4S},[X2]'​

Another issues seen in litmus test for address dependency between a
load and Neon store

$ diyone7  -arch AArch64 -variant neon "Rfe PodRW Rfe DpAddrdWPN2 PodWW"​

---cut---

P0          | P1                         ;​
LDR W1,[X0] | ...                        ;​
MOV W2,#1   | ...                        ;​
STR W2,[X3] | EOR W2,W1,W1               ;​ (* A *)
            | EOR X3,X2,X2               ;​
            | MOVI V0.4S,#1              ;​
            | MOVI V1.4S,#2              ;​
            | ST2 {V0.4S, V1.4S},[X4],X3 ;​ (* B *)
            | MOV W5,#1                  ;​
            | STR W5,[X6]                ;​

---cut---

First of all unnecessary exclusive or at A, yet it doesn't
hurt. Second, Neon store at B​ uses post-index form where X3 would be
consumed after access is made to update X4, in other words, X3 doesn't
contribute to the address generation for ST2 access at B.

Also, there are numerous cases where litmus test generation would fail
with

 Fatal error: exception File "lib/AArch64Base.ml", line 317, characters 48-54: Assertion failed​
​
So, rework STN such that

* For data dependency between a load and Neon store we produce code
  sequence like

 DUP V3.4S,W2            ;​ (* expand W2 into V3 *)
 MOVI V4.4S,#0           ;​
 MOVI V5.4S,#1           ;​
 ADD V4.4S,V4.4S,V3.4S   ;​ (* V4 depends on V3 *)
 ADD V5.4S,V5.4S,V3.4S   ;​ (* V5 depends on V3 *)
 ST2 {V4.4S, V5.4S},[X3] ; (* Store both V4 and V3 *)

* For address dependency between a load and Neon store we produce code
  sequence like ​

 ADD X4,X3,W1,SXTW       ; (* X4 depends on X3 (generated by previous load) *) ​
 MOVI V0.4S,#1           ;​
 MOVI V1.4S,#2           ;​
 ST2 {V0.4S, V1.4S},[X4] ;​ (* ST2 consumes X4 *)
​

Signed-off-by: Vladimir Murzin <vladimir.murzin@arm.com>