Neon update
This is a combination of 16 commits.

[tests]: Fix Neon tests V44 and V45

Encoding of immediate for 64-bit variant of MOVI instruction is
different to 32-bit

MOVI <Dd>, #<imm>

where

<imm>
Is a 64-bit immediate 'aaaaaaaabbbbbbbbccccccccddddddddeeeeeeeeffffffffgggggggghhhhhhhh',
encoded in "a:b:c:d:e:f:g:h".

Unfortunately, that was overlooked for tests V44 and V45, which are failing to build:

/tmp/ccJAwX0B.s:126: Error: invalid value for immediate at operand 2 -- `movi d1,#254'
make: *** [Makefile:39: V44.o] Error 1

/tmp/ccX7x0v3.s: Assembler messages:
/tmp/ccX7x0v3.s:487: Error: invalid value for immediate at operand 2 -- `movi d2,#254'

Fix that by using acceptable immediates

[litmus]: Fix build neon tests for -mode presi

`-mode presi` doen't know about typdef for register output so build
failing with

V34.c:197:3: error: unknown type name ‘int_4_t’
  197 |   int_4_t out_0_v0;
      |   ^~~~~~~
V34.c: In function ‘pp_log’:

Let's move `dump_array_typedefs` into common place and use in both
`std` and `presi` modes

[litmus]: Add comments for handling initialization of Neon registers

It might look confusing why for some instructions cleraly output
registers are going into 'inputs'. The reason is that such
instructions can insert data into individual elements of Neon register
without clearing the remaining bits to zero, thus to guarantee that
unaffected bits are zero the whole Neon register need to be
zero-initialized prior the use.

Several options have been evaluated [1] and it seems the only robust
way to achieve that is using the constraint "+" combined with the
explicit initialization of the 'stable_*' variables.

So, lets add comments to relevant parts to save time digging up history
next time somebody get confused.

[1] https://github.com/herd/herdtools7/pull/131

[litmus]: add MOV (from general) to stable regs

This instruction can insert data into individual elements within a
SIMD&FP register without clearing the remaining bits to zero

[litmus]: add MOV (element) to stable regs

This instruction can insert data into individual elements within a
SIMD&FP register without clearing the remaining bits to zero

[all]: Add support for DUP

[all]: Add partial support for FMOV (general)

[all]: Add support for ADDV

[gen]: Rework LDN

Unfortunately, there are several issues with litmus test generation
when it comes to broad use Neon annotations.

For example, litmus test for data dependency between Neon load and a
store comes with several issues

$ diyone7  -arch AArch64 -variant neon "Rfe PodRW Rfe DpDatadWN2N2"​

---cut---

P0          | P1                      ;​
LDR W1,[X0] | LD2 {V0.4S, V1.4S},[X0] ; (* A *)​
MOV W2,#1   | EOR V2.4S,V0.4S,V0.4S   ;​ (* B *)
STR W2,[X3] | ...                     ;​

---cut---

First, result of load into V1 at A is not consumed. Second,
instruction at B is not valid:

 Assembler messages:​
  Error: operand mismatch -- `eor V2.4S,V0.4S,V0.4S'​
  Info:    did you mean this?​
  Info:    eor v1.8b, v0.8b, v0.8b​
  Info:    other valid variant(s):​
  Info:    eor v1.16b, v0.16b, v0.16b​

Another issue can be seen in litmus test for address dependency
between a load and Neon load

$ diyone7  -arch AArch64 -variant neon "PodWW Rfe DpAddrdRPN2 Fre"​

---cut---

P0          | P1                         ;​
MOV W0,#1   | ...                        ;​
STR W0,[X1] | ...                        ;​
MOV W2,#1   | ...                        ;​
STR W2,[X3] | LD2 {V0.4S, V1.4S},[X4],X3 ; (* A *)​

---cut--

Neon load at A​ uses post-index form where X3 would be consumed after
access is made to update X4, in other words, X3 doesn't contribute to
the address generation for LD2 access at A.

Also, there are numerous cases where litmus test generation would fail
with

 Fatal error: exception File "lib/AArch64Base.ml", line 317, characters 48-54: Assertion failed​

To make things work we need to rework LDN. For things like address
dependency and control dependency we need to reduce vector registers
horizontally (in case more than one vector register is used) follow up
with reduce horizontally single vector register into scalar, so it can
be transferred to general purpose register and become available either
for address generation logic or control flow logic.

In term of instruction that reduction looks like

 LD2 {V0.4S, V1.4S},[X0] ;​
 ADD V0.4S,V0.4S,V1.4S   ;​ (* reduce (and consume) V0 and V1 into V0 *)
 ADDV S2,V0.4S           ;​ (* reduce V0 inot S2 *)
 FMOV W1,S2              ; (* transfer S2 into W1 *)

The only downside is that for data dependency between, say, Neon load
and Neon store data have to trip via general purpose register which is
sub-optimal

 LD2 {V0.4S, V1.4S},[X0] ;​
 ADD V0.4S,V0.4S,V1.4S   ;​
 ADDV S2,V0.4S           ;​
 FMOV W1,S2              ;​
 EOR W2,W1,W1            ;​
 DUP V3.4S,W2            ;​
 MOVI V4.4S,#1           ;​
 MOVI V5.4S,#2           ;​
 ADD V4.4S,V4.4S,V3.4S   ;​
 ADD V5.4S,V5.4S,V3.4S   ;​
 ST2 {V4.4S, V5.4S},[X3] ;​

However, when it comes to data dependency, say, between Neon load and
non-Neon store things look more natural

 LD2 {V0.4S, V1.4S},[X0] ;​
 ADD V0.4S,V0.4S,V1.4S   ;​
 ADDV S2,V0.4S           ;​
 FMOV W1,S2              ;​
 EOR W2,W1,W1            ;​
 ADD W2,W2,#1            ;​
 STR W2,[X3]             ;​

[gen]: Rework STN

Unfortunately, there are several issues with litmus test generation
when it comes to broad use Neon annotations.

For example, litmus test for data dependency between a load and Neon
store comes with use of invalid instruction

$ diyone7  -arch AArch64 -variant neon "Rfe PodRW Rfe DpDatadWN2N2"​

---cut---

P0          | P1                      ;​
LDR W1,[X0] | ...                     ;​
MOV W2,#1   | ...                     ;​
STR W2,[X3] | MOVI V3.4S,#1           ;​
            | ADD V2.4S,V2.4S,V3.4S   ;​
            | ST2 {V2.4S},[X2]        ;​ (* A *)
---cut---

Neon's ST2 at A is invalid:

Error: invalid number of registers in the list; 2 registers are
expected at operand 1 -- `st2 {V2.4S},[X2]'​

Another issues seen in litmus test for address dependency between a
load and Neon store

$ diyone7  -arch AArch64 -variant neon "Rfe PodRW Rfe DpAddrdWPN2 PodWW"​

---cut---

P0          | P1                         ;​
LDR W1,[X0] | ...                        ;​
MOV W2,#1   | ...                        ;​
STR W2,[X3] | EOR W2,W1,W1               ;​ (* A *)
            | EOR X3,X2,X2               ;​
            | MOVI V0.4S,#1              ;​
            | MOVI V1.4S,#2              ;​
            | ST2 {V0.4S, V1.4S},[X4],X3 ;​ (* B *)
            | MOV W5,#1                  ;​
            | STR W5,[X6]                ;​

---cut---

First of all unnecessary exclusive or at A, yet it doesn't
hurt. Second, Neon store at B​ uses post-index form where X3 would be
consumed after access is made to update X4, in other words, X3 doesn't
contribute to the address generation for ST2 access at B.

Also, there are numerous cases where litmus test generation would fail
with

 Fatal error: exception File "lib/AArch64Base.ml", line 317, characters 48-54: Assertion failed​
​
So, rework STN such that

* For data dependency between a load and Neon store we produce code
  sequence like

 DUP V3.4S,W2            ;​ (* expand W2 into V3 *)
 MOVI V4.4S,#0           ;​
 MOVI V5.4S,#1           ;​
 ADD V4.4S,V4.4S,V3.4S   ;​ (* V4 depends on V3 *)
 ADD V5.4S,V5.4S,V3.4S   ;​ (* V5 depends on V3 *)
 ST2 {V4.4S, V5.4S},[X3] ; (* Store both V4 and V3 *)

* For address dependency between a load and Neon store we produce code
  sequence like ​

 ADD X4,X3,W1,SXTW       ; (* X4 depends on X3 (generated by previous load) *) ​
 MOVI V0.4S,#1           ;​
 MOVI V1.4S,#2           ;​
 ST2 {V0.4S, V1.4S},[X4] ;​ (* ST2 consumes X4 *)
​

[gen]: Rename Neon annotations

Currently, Neon annotations are mapped to instruction as

* N1 -> LD1/ST1 (1 register)
* N2 -> LD2/ST2 (2 register)
* N3 -> LD3/ST3 (3 register)
* N4 -> LD4/ST4 (4 register)

Basically reflecting how many registers consumed by family of
load/store multiple structure instructions. However, that naming is
not flexible enough when it comes to extending Neon support with other
variants or even non-interleaving LD1/ST1 which can accept up to 4
registers.

So, let's make some (name)space for Neon annotations:

* Ne1 -> LD1/ST1 (1 register)
* Ne2i -> LD2/ST2 (2 register)
* Ne3i -> LD3/ST3 (3 register)
* Ne4i -> LD4/ST4 (4 register)

Where we preserve an idea of amount of registers required by
instructions, yet additionally highlight that some annotations would
result in interleaving (i) Neon load/store instructions.

[herd]: Complete support for LD1/ST1

LD1/ST1 are non-interleave (contiguous) load/store and can use up to 4
registers. However, current implementation tend to correlate number of
registers used by instructions with interleave pattern and unnecessary
put limitation on LD1 having just single register.

Let's complete support for LD1/ST1 and allow more than one register.

[gen]: Complete support for LD1/ST1

Provide annotation to emmit non-interleave LD1/ST1 instructions with
more than one register:

 Ne1 -> LD1 {reg}
 Ne2 -> LD1 {reg,reg}
 Ne3 -> LD1 {reg,reg,reg}
 Ne4 -> LD1 {reg,reg,reg,reg}

[litmus]: Utilize Arm Neon intrinsics for Neon tests

It was noticed that for some litmus test generated code could not
build.

For instance

AArch64 A
{
 0:X0=1;
}
 P0                    ;
 B END                 ;
 MOV V0.S[0], W0       ;
END:                   ;
 exists (0:V0.4S={1,0,0,0})

results into

T.c: In function ‘P0’:
T.c:195:10: error: cast specifies array type
  195 | :"[v0]" ((int_4_t)(0)),[x0] "r" ((int)(0))
      |          ^

where int_4_t is an alias to int[4]

Let's use Arm Neon intrinsics and types [1] to handle register
initialization.

For that we (ab)use `internal_init` and make it return register
initialization string and type string. Register initialization usually
assumes some initial value so `internal_init` is extended to take
optional string representing the value. Rest of the code is adopted to
benefit from the new functionality.

[1] https://arm-software.github.io/acle/neon_intrinsics/advsimd.html

Update tests for litmus to accept them

For making litmus happy, the following changes apply:
  1. V10 and V45 change type of `y` to `int64_t`.
    Namely as the test stores a 64bit integer to y, sizes must
    match. Otherwise the produced executable may crash or produce
    wrong results.
  2. V43, V46 and V47 restore address register to an exact symbolic
     value, thereby cancelling the effect of post-index addressing.
     Namely, litmus7 cannot print symbolic values of the forme
     x+offset.
  3. V47 specify type `int64_t` for the register 0:X1 that is used
     as an `X` register in test code and initialised. This mundane
     changes avoids a warning.

Also add test V64 (which identified a problem) and
update reference files accordingly.

Co-authored-by: Luc Maranget <Luc.Maranget@inria.fr>
Signed-off-by: Vladimir Murzin <vladimir.murzin@arm.com>