fix(lib): wait for process before calling channel functions
Running `make test` directly will result in the following failure:

Fatal error: exception Failure("Herd returned stderr: Warning: File
\"catalogue/aarch64-MTE/tests/to-tagcheck-async/MP+dmb.st+acqrel_and_ctrl--async.litmus\":
unrolling limit exceeded at L0, legal outcomes may be missing.")

`make test DUNE_PROFILE=dev` on the other hand succeeds (as is used in
the CI).

I suspect the reason is the `dev` profile doesn't wait for the spawned
`herd` process to finish before calling the function to collect the
`stderr` result.

This commit moves the function calls to after the process is finished or
an exception is raised.