[litmus]: Utilize Arm Neon intrinsics for Neon tests
It was noticed that for some litmus test generated code could not
build.

For instance

AArch64 A
{
 0:X0=1;
}
 P0                    ;
 B END                 ;
 MOV V0.S[0], W0       ;
END:                   ;
 exists (0:V0.4S={1,0,0,0})

results into

T.c: In function ‘P0’:
T.c:195:10: error: cast specifies array type
  195 | :"[v0]" ((int_4_t)(0)),[x0] "r" ((int)(0))
      |          ^

where int_4_t is an alias to int[4]

Let's use Arm Neon intrinsics and types [1] to handle register
initialization.

For that we (ab)use `internal_init` and make it return register
initialization string and type string. Register initialization usually
assumes some initial value so `internal_init` is extended to take
optional string representing the value. Rest of the code is adopted to
benefit from the new functionality.

[1] https://arm-software.github.io/acle/neon_intrinsics/advsimd.html

Signed-off-by: Vladimir Murzin <vladimir.murzin@arm.com>